[package]
name = "lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["cookie"] }
bb8 = "0.9.1"
dotenvy = "0.15.7"
oauth2 = "5.0.0"
redis = { version = "1.7.0", features = ["tokio-rustls-comp", "bb8", "uuid", "tls-rustls-webpki-roots"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
time = "0.3.55"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7.1", features = ["fs"] }
uuid = { version = "1.26.1", features = ["v7", "v4"] }
